# Generated by Django 4.1.7 on 2023-03-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_members_gob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Gob',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
