# Generated by Django 4.1.7 on 2023-03-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_members_gob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default='FREE', max_digits=5)),
                ('image', models.ImageField(default='photos/news-02.png', upload_to='')),
                ('date_creat', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
