# Generated by Django 4.1.7 on 2023-03-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='date_join',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
