# Generated by Django 4.1.7 on 2023-03-16 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_premium_remove_members_gender_members_gob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Premium',
        ),
    ]
