# Generated by Django 4.1.7 on 2023-03-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_delete_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='firstName',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
