# Generated by Django 4.1.7 on 2023-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_alter_members_email_alter_members_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='Gob',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
