# Generated by Django 4.1.7 on 2023-03-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0016_remove_members_id_alter_members_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='cours',
        ),
        migrations.AddField(
            model_name='members',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
