# Generated by Django 4.1.7 on 2023-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_alter_members_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
