# Generated by Django 4.1.7 on 2023-03-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_alter_members_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='id1',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
