# Generated by Django 4.1.7 on 2023-03-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0020_members_id1_alter_members_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='labelwasf',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
