# Generated by Django 4.1.7 on 2023-03-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_courses_labelwasf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='labelwasf',
        ),
    ]
