# Generated by Django 4.1.7 on 2023-03-16 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0022_remove_courses_labelwasf'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.courses'),
        ),
    ]
