# Generated by Django 4.1.7 on 2023-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0023_members_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='section',
            new_name='cours',
        ),
        migrations.RemoveField(
            model_name='members',
            name='id1',
        ),
    ]
