# Generated by Django 4.1.7 on 2023-03-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0025_alter_members_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
