# Generated by Django 4.1.7 on 2023-03-16 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0029_alter_courses_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='member',
        ),
        migrations.AddField(
            model_name='members',
            name='cours',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.courses'),
        ),
    ]
