# Generated by Django 4.1.7 on 2023-03-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0031_remove_members_cours_members_cours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='firstName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='lastName',
            new_name='lName',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
    ]
