# Generated by Django 4.1.7 on 2023-03-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0032_rename_firstname_members_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
    ]
